# Configuration des routes

home:
  path: /
  controller: App\Controller\SiteAnnoncesImmoController::index

propertie_add:
  path: site_annonces_immo/add
  controller: App\Controller\SiteAnnoncesImmoController::add

propertie_show:
  path: site_annonces_immo/show/{id}
  controller: App\Controller\SiteAnnoncesImmoController::show

propertie_edit:
  path: site_annonces_immo/edit/{id}
  controller: App\Controller\SiteAnnoncesImmoController::edit
  requirements:
    id: '\d+'

propertie_delete:
  path: site_annonces_immo/delete/{id}
  controller: App\Controller\SiteAnnoncesImmoController::delete
  requirements:
    id: '\d+'